### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by pwalsh** [openspending/os-upload#14]
The data load UI for OpenSpending is largely a client-side affair, at least in the first iteration.

So, we will be using the majority of the dependencies that have have in [DataPackagist](https://github.com/okfn/datapackagist), as behind the scenes the requirements and data flows are the same, even if the UI is very different.

Even though it is a client-side app, we are going to host it in a small server for convenience of routing, etc., and for this we will use Express.js on top of io.js. We are using io.js instead of node.js because of support for Zombie.js, which helps with fast functional testing ([Example from DataPackgist](https://github.com/okfn/datapackagist/blob/master/tests/index.js)).

## Tasks

* [x] Setup Express and Gulp as per DataPackagist config
* [x] Setup all the base dependencies
* [x] Code management:
  * Copy current master branch to "upload-old" branch
  * Start new develop branch with clean slate (no history)
  * Make develop the default branch
  * Remove master branch and start again, or, clear master branch
* [x] Setup a dedicated route for the landing page
* [x] Setup a dedicated route for hosting the actual dataload app
* [x] Write a a few small tests to show we are setup correctly

**Comment by gvidon** [comment]
- [x] install linter, remove rule that forces to use single char vars in lambdas

**Comment by gvidon** [comment]
Introduced new npm command which throws messages in stderr in case of js linting errors

``` shell
npm run lint_js
```

**Comment by gvidon** [comment]
From now on there is nothing in `os-upload/dist/` dir what cannot be safely removed.

**Comment by pwalsh** [comment]
FIXED.
