### ISSUE TITLE
Import step 3 - Add metadata to the package

### ISSUE THREAD

**Issue by pwalsh** [openspending/os-upload#20]
# Description

After the user has provided additional information to describe her data in step 2, we will collect additional metadata. This will be a basic set of forms of similar style to the elements in Step 1
# Tasks
- [ ] **Title**: The name field that we removed from Step 1 now gets added as the first input in this form
- [ ] **Short description**: A free text field for the user to describe the dataset
- [ ] **Location**: A fieldset with the following fields. Can select all or none:
  - [ ] **Region**: A list of all regions. Can select one or many. (@pwalsh can provide an example list. We'll hard code it for now but we may aim to break this into a service later)
  - [ ] **Country**: A list of all countries. Can select one or many. (@pwalsh can provide an example list. We'll hard code it for now but we may aim to break this into a service later)
  - [ ] **City**: Enter the name of a city
- [ ] **Period**: Start date <-> End date
- [ ] All of these data inputs are properties of the top-level DataPackage object
- [ ] NEXT button as per previous steps - available when minimum requirements are met (Title is populated)
  - [ ] At this step, you need to run `datapackage-validate` over the package, and display any errors if the package is not valid. Also note that **if** we have errors, they are errors in our logic somewhere, as the whole package has been created programmatically :)
- [ ] Tests for their presence/absence on the Data Package object
- [ ] Tests for form interaction

**Comment by gvidon** [comment]
@pwalsh 
- should **City** be an autocomplete field?
- do we use datepicker widget for **Period**?

**Comment by pwalsh** [comment]
City: no, just free entry for this iteration.
Period: ok, but just something generic now

**Comment by rufuspollock** [comment]
Period is almost certain a year not a specific date (but not always) - so you probably don't want a date picker.

**Comment by gvidon** [comment]
@pwalsh @rgrp ok
- no autocomplete for **City**
- just year in **Period**, no date picker.
